### ISSUE TITLE
option to make all issues warnings

### ISSUE THREAD

**Issue by benmosher** [SublimeLinter/SublimeLinter-pep8#13]
Hello,

I'd personally prefer pep8 issues were classified as warnings instead of errors.

Would it be straightforward to expose a linter option to switch modes? Currently, I believe all pep8 issues are always reported as errors. It would make sense to me to keep this as the default, but allow some `log_as_warnings: true` option that could be set in linter settings alongside the ignored rule types.

Thanks!

**Comment by braver** [comment]
SublimeLinter 4 (currently in beta) will support several kinds of filtering and tweaking of colors, which should allow you to address this. We're not going to be able to really something sensible about it just for this plugin.
