### ISSUE TITLE
Fail gracefully if .sublimelinterrc has a UTF-8 signature/BOM

### ISSUE THREAD

**Issue by mchubby** [SublimeLinter/SublimeLinter-pep8#18]
Currently the console logs a generic error `"No JSON object could be decoded"` while the JSON passes if you copy-paste it in a validator, which can be confusing.

Fail gracefully if a UTF-8 signature has been detected in `.sublimelinterrc`

**Comment by braver** [comment]
If this is still an problem, please open an issue over at the main SublimeLinter3 repo.
